language: node_js
node_js: 
  - "stable"

env:
  - automart_jwtPrivateKey="mysecureKey"

install:
  - npm install

script:
  - npm test
  
cache:
  directories:
    - "node_modules"

after_success: npm run coverage