language: node_js
node_js: 
  - "stable"

env:
  - automart_jwtPrivateKey="mysecureKey"
  - cloud_name='hjdhdhsh'
  - api_key='56678878'
  - api_secret='54555665'

install:
  - npm install

script:
  - npm test

cache:
  directories:
    - "node_modules"

after_success: npm run coverage