language: node_js
node_js: 
  - "stable"

env:
  - automart_jwtPrivateKey="mysecureKey"
  - cloud_name="dvhepwf18"
  - api_key="587784587126295"
  - api_secret="2O2vQ9YNbRgLrzwLHGsPLY4Dpc8"

install:
  - npm install

script:
  - npm test

cache:
  directories:
    - "node_modules"

after_success: npm run coverage