language: node_js
node_js: 
  - "stable"

services:
  - postgresql 

before_script:
  - psql -c 'create database AutoMartDB;' -U postgres
  - travis_wait npm install

addons:
  - postgresql: "10.5"

env:
  - automart_jwtPrivateKey="mysecureKey"
 

install:
  - npm install

script:
  - npm test

cache:
  directories:
    - "node_modules"

after_success: npm run coverage