language: node_js
node_js: 
  - "stable"

services:
  - postgresql 

install:
  - npm install

addons:
  - postgresql: "10.5"

before_script:
  - travis_wait npm install
  - psql -c 'create database automart_db;' -U postgres
  - "npm run create"

env:
  - automart_jwtPrivateKey="mysecureKey"
 
script:
  - npm test

cache:
  directories:
    - "node_modules"

after_success: npm run coverage